spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: TencentMysql@2019
    url: jdbc:mysql://139.199.94.62:3306/bootdb?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell
management:
  endpoints:
    web:
      exposure:
        include: '*'
wechat:
  appId: wxccac1f71a22dd43b
  appSecret: c17da0c6601aa1a21ef706d2270a0054